### ISSUE TITLE
3d rendering

### ISSUE THREAD

**Issue by PolarBean** [yxu233/Xu_Bergles_brainwide_oligo_map#2]
I have previously worked on rendering lightsheet volumes in 3D using neuroglancer and I thought it might be useful for you. 

[here is a link to the 3D volume rendering. ](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B0.000001152035240378141%2C%22m%22%5D%2C%22y%22:%5B0.000001152035240378141%2C%22m%22%5D%2C%22z%22:%5B0.000005%2C%22m%22%5D%7D%2C%22position%22:%5B5643.28759765625%2C6024.4921875%2C-919.5%5D%2C%22crossSectionScale%22:30.010120696498806%2C%22projectionOrientation%22:%5B0.021819045767188072%2C0.028280919417738914%2C-0.16131989657878876%2C-0.9862555265426636%5D%2C%22projectionScale%22:22264.756486600876%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://https://xu-bergles-oligo-maps.s3.amazonaws.com/M260_MoE_P60/setup0/timepoint0/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C-1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B0.000001152035240378141%2C%22m%22%5D%2C%22y%22:%5B0.000001152035240378141%2C%22m%22%5D%2C%22z%22:%5B0.000005%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22shader%22:%22#uicontrol%20invlerp%20normalized%5Cnvoid%20main%20%28%29%20%7B%5Cn%20%20float%20x%20=%20float%28normalized%28%29%29%3B%5Cn%20%20if%20%28x%20%3C%200.09%29%20%7B%5Cn%20%20%20%20x%20=%200.0%3B%5Cn%20%20%7D%5Cn%20%20emitRGBA%28vec4%28x%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20x%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20x%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20clamp%28x%2C0.0%2C256.0%29%29%29%3B%5Cn%7D%5Cn%5Cn%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B0%2C1102%5D%7D%7D%2C%22volumeRendering%22:%22on%22%2C%22name%22:%22timepoint0%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22size%22:309%2C%22layer%22:%22timepoint0%22%7D%2C%22crossSectionBackgroundColor%22:%22#171717%22%2C%22layout%22:%22xy-3d%22%7D)

**Comment by tigeryuxu** [comment]
oh very cool, thank you! I didn't know neuroglancer could render raw data. I thought it was only segmentations. Good to know!

**Comment by PolarBean** [comment]
no worries!
